### PR TITLE
Complete project

### PR DESCRIPTION
**Pull request by toliboff**
## The project is a single-page application (SPA) built with React and Redux.

In this PR were implemented following:
- Used Financial modeling prep API to fetch data
- The data retrieved from the API is stored in the Redux store.
- Filtered data retrieved from the API
- Every page (the main page and the pages for each item) has a unique route within the SPA.
- The project was deployed on Netlify and accessible online
- Created unit tests for pure functions in Redux code.
- Create integration tests using the React Testing Library.
- Mocked the access to the API

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [x] Please use a `Filter` stateless component to filter data retrieved from the API. 
- [x] The video you created should contain a highlight about a piece of the code you find interesting or proud of making.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by toliboff** [comment]
Hi @arslanbisharat 

Thank you for your time and effort in pointing out these changes in this review. 
Yes, the project has a requirement to use the `Filter` stateless component. I would like to learn more about it and could you please, in short, explain how to implement `Filter` stateless component in my case? I asked about it, my coding partners, and other students. They don't have a clear understanding of what does it mean. 
Thank you in advance.

**Comment by arslanbisharat** [comment]
Hi there, Please schedule a 1:1 meeting with SCR. You will get more
insights.

Have a nice weekend.

Best,
Arslan Bisharat

**Comment by toliboff** [comment]
- Implemented required changes.
- Updated video presentation link

**Review by Georjane — APPROVED** [review]
## Status: PR Approved 💯 🥇 
#### Hello @toliboff, 

Your project is complete!  You have met all requirements for this project. It is a thumbs up for me. 👍🏽 You can go ahead and merge this PR. 
Congratulations! 🎉 👏👏

_Good luck with your next project and Happy coding!_ 💻

**Pull request merged**
